// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	UserID         int64
	Username       string
	HashedPassword string
	UserToken      pgtype.UUID
}
