// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkUserToken = `-- name: CheckUserToken :one
SELECT user_id, username, hashed_password, user_token
FROM users
WHERE user_token = $1
`

func (q *Queries) CheckUserToken(ctx context.Context, db DBTX, userToken pgtype.UUID) (User, error) {
	row := db.QueryRow(ctx, checkUserToken, userToken)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.HashedPassword,
		&i.UserToken,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username, hashed_password, user_token
) VALUES ( $1, $2, uuid_generate_v4() )
RETURNING user_id, username, hashed_password, user_token
`

type CreateUserParams struct {
	Username       string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) (User, error) {
	row := db.QueryRow(ctx, createUser, arg.Username, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.HashedPassword,
		&i.UserToken,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE user_id = $1
	AND user_token = $2
`

type DeleteUserParams struct {
	UserID    int64
	UserToken pgtype.UUID
}

func (q *Queries) DeleteUser(ctx context.Context, db DBTX, arg DeleteUserParams) error {
	_, err := db.Exec(ctx, deleteUser, arg.UserID, arg.UserToken)
	return err
}

const getUser = `-- name: GetUser :one
SELECT user_id, username, hashed_password, user_token
FROM users
WHERE username = $1
  AND hashed_password = $2
`

type GetUserParams struct {
	Username       string
	HashedPassword string
}

func (q *Queries) GetUser(ctx context.Context, db DBTX, arg GetUserParams) (User, error) {
	row := db.QueryRow(ctx, getUser, arg.Username, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.HashedPassword,
		&i.UserToken,
	)
	return i, err
}

const getUserFromID = `-- name: GetUserFromID :one
SELECT user_id, username, hashed_password, user_token
FROM users
WHERE user_id = $1
`

func (q *Queries) GetUserFromID(ctx context.Context, db DBTX, userID int64) (User, error) {
	row := db.QueryRow(ctx, getUserFromID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.HashedPassword,
		&i.UserToken,
	)
	return i, err
}

const getUserToken = `-- name: GetUserToken :one
SELECT user_token
FROM users
WHERE user_id = $1
`

func (q *Queries) GetUserToken(ctx context.Context, db DBTX, userID int64) (pgtype.UUID, error) {
	row := db.QueryRow(ctx, getUserToken, userID)
	var user_token pgtype.UUID
	err := row.Scan(&user_token)
	return user_token, err
}

const resetUserToken = `-- name: ResetUserToken :one
UPDATE users
SET user_token = uuid_generate_v4()
WHERE user_id = $1
RETURNING user_id, username, hashed_password, user_token
`

func (q *Queries) ResetUserToken(ctx context.Context, db DBTX, userID int64) (User, error) {
	row := db.QueryRow(ctx, resetUserToken, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.HashedPassword,
		&i.UserToken,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
	SET username = $1,
    hashed_password = $2
WHERE user_id = $3
RETURNING user_id, username, hashed_password, user_token
`

type UpdateUserParams struct {
	Username       string
	HashedPassword string
	UserID         int64
}

func (q *Queries) UpdateUser(ctx context.Context, db DBTX, arg UpdateUserParams) (User, error) {
	row := db.QueryRow(ctx, updateUser, arg.Username, arg.HashedPassword, arg.UserID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.HashedPassword,
		&i.UserToken,
	)
	return i, err
}
